In [ ]:
# pandas library is used for read and process data
import pandas as pd

In [ ]:
df = pd.read_csv('weather_data_nyc.csv')
df

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth
0,1-1-2016,42,34,38.0,0.00,0.0,0
1,2-1-2016,40,32,36.0,0.00,0.0,0
2,3-1-2016,45,35,40.0,0.00,0.0,0
3,4-1-2016,36,14,25.0,0.00,0.0,0
4,5-1-2016,29,11,20.0,0.00,0.0,0
...,...,...,...,...,...,...,...
361,27-12-2016,60,40,50.0,0,0,0
362,28-12-2016,40,34,37.0,0,0,0
363,29-12-2016,46,33,39.5,0.39,0,0
364,30-12-2016,40,33,36.5,0.01,T,0
365,31-12-2016,44,31,37.5,0,0,0

In [ ]:
  df['maximum temperature'].max()

96

In [14]:
# Convert 'T' and other non-numeric entries to NaN, then fill them with 0
df['precipitation_clean'] = pd.to_numeric(df['precipitation'], errors='coerce').fillna(0)

# Now filter for dates with actual rain
rain_dates = df['date'][df['precipitation_clean'] > 0]
print(rain_dates)

9       10-1-2016
15      16-1-2016
16      17-1-2016
21      22-1-2016
22      23-1-2016
          ...
352    18-12-2016
358    24-12-2016
360    26-12-2016
363    29-12-2016
364    30-12-2016
Name: date, Length: 116, dtype: object

In [16]:
# Remove any leading/trailing whitespace from all column names
df.columns = df.columns.str.strip()

# Now you can safely access the column
print(df['average temperature'].mean())

57.21584699453552

In [17]:
# dataframes in pandas
df.shape

(366, 8)

In [19]:
df.head() # prints few rows of data

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth,precipitation_clean
0,1-1-2016,42,34,38.0,0.00,0.0,0,0.0
1,2-1-2016,40,32,36.0,0.00,0.0,0,0.0
2,3-1-2016,45,35,40.0,0.00,0.0,0,0.0
3,4-1-2016,36,14,25.0,0.00,0.0,0,0.0
4,5-1-2016,29,11,20.0,0.00,0.0,0,0.0

In [20]:
df.tail() # prints few rows of data

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth,precipitation_clean
361,27-12-2016,60,40,50.0,0,0,0,0.00
362,28-12-2016,40,34,37.0,0,0,0,0.00
363,29-12-2016,46,33,39.5,0.39,0,0,0.39
364,30-12-2016,40,33,36.5,0.01,T,0,0.01
365,31-12-2016,44,31,37.5,0,0,0,0.00

In [21]:
# slicing
df[2:5]

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth,precipitation_clean
2,3-1-2016,45,35,40.0,0.00,0.0,0,0.0
3,4-1-2016,36,14,25.0,0.00,0.0,0,0.0
4,5-1-2016,29,11,20.0,0.00,0.0,0,0.0

In [22]:
df.columns

Index(['date', 'maximum temperature', 'minimum temperature',
       'average temperature', 'precipitation', 'snow fall', 'snow depth',
       'precipitation_clean'],
      dtype='object')

In [23]:
df.date

0        1-1-2016
1        2-1-2016
2        3-1-2016
3        4-1-2016
4        5-1-2016
          ...
361    27-12-2016
362    28-12-2016
363    29-12-2016
364    30-12-2016
365    31-12-2016
Name: date, Length: 366, dtype: object

In [24]:
df['date']

0        1-1-2016
1        2-1-2016
2        3-1-2016
3        4-1-2016
4        5-1-2016
          ...
361    27-12-2016
362    28-12-2016
363    29-12-2016
364    30-12-2016
365    31-12-2016
Name: date, Length: 366, dtype: object

In [25]:
df[['date','precipitation']]

           date precipitation
0      1-1-2016          0.00
1      2-1-2016          0.00
2      3-1-2016          0.00
3      4-1-2016          0.00
4      5-1-2016          0.00
..          ...           ...
361  27-12-2016             0
362  28-12-2016             0
363  29-12-2016          0.39
364  30-12-2016          0.01
365  31-12-2016             0

[366 rows x 2 columns]

In [27]:
df['maximum temperature'].describe()

count    366.000000
mean      64.625683
std       18.041787
min       15.000000
25%       50.000000
50%       64.500000
75%       81.000000
max       96.000000
Name: maximum temperature, dtype: float64

In [30]:
df[df['maximum temperature'] == df['maximum temperature'].max()]

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth,precipitation_clean
204,23-7-2016,96,80,88.0,0,0,0,0.0
225,13-8-2016,96,81,88.5,0,0,0,0.0

In [31]:
df.date[df['maximum temperature'] == df['maximum temperature'].max()]

204    23-7-2016
225    13-8-2016
Name: date, dtype: object

In [49]:
# read and write in csv and xls files
df = pd.read_excel('weather_data_nyc.xlsx')
df

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth
0,2016-01-01,42,34,38.0,0,0,0
1,2016-01-02,40,32,36.0,0,0,0
2,2016-01-03,45,35,40.0,0,0,0
3,2016-01-04,36,14,25.0,0,0,0
4,2016-01-05,29,11,20.0,0,0,0
...,...,...,...,...,...,...,...
361,2016-12-27,60,40,50.0,0,0,0
362,2016-12-28,40,34,37.0,0,0,0
363,2016-12-29,46,33,39.5,0.39,0,0
364,2016-12-30,40,33,36.5,0.01,T,0
365,2016-12-31,44,31,37.5,0,0,0

In [50]:
df.to_csv('new.csv') # index will be stored here
df.to_csv('new_noindex.csv', index=False) # index will not be stored here
# aslo we can save data in excel file

In [51]:
g = df.groupby('maximum temperature')
g

In [56]:
for temperature, df in g:
    print(temperature)
    print(df)

15
         date  maximum temperature  minimum temperature  average temperature  \
44 2016-02-14                   15                   -1                  7.0

   precipitation snow fall snow depth
44             0         0          0
22
         date  maximum temperature  minimum temperature  average temperature  \
43 2016-02-13                   22                    6                 14.0

   precipitation snow fall snow depth
43             0         0          0
27
          date  maximum temperature  minimum temperature  average temperature  \
22  2016-01-23                   27                   24                 25.5
42  2016-02-12                   27                   15                 21.0
350 2016-12-16                   27                   17                 22.0

    precipitation snow fall snow depth
22           2.31      27.3          6
42              0         0          0
350             0         0          0
28
         date  maximum temperature  minimum temperature  average temperature  \
18 2016-01-19                   28                   16                 22.0

   precipitation snow fall snow depth
18             0         0          T
29
        date  maximum temperature  minimum temperature  average temperature  \
4 2016-01-05                   29                   11                 20.0

  precipitation snow fall snow depth
4             0         0          0
30
         date  maximum temperature  minimum temperature  average temperature  \
12 2016-01-13                   30                   22                 26.0
21 2016-01-22                   30                   21                 25.5

   precipitation snow fall snow depth
12             0         0          0
21          0.01       0.2          0
31
          date  maximum temperature  minimum temperature  average temperature  \
17  2016-01-18                   31                   18                 24.5
41  2016-02-11                   31                   18                 24.5
353 2016-12-19                   31                   23                 27.0

    precipitation snow fall snow depth
17              T         T          T
41              T         T          0
353             0         0          0
33
          date  maximum temperature  minimum temperature  average temperature  \
354 2016-12-20                   33                   20                 26.5

    precipitation snow fall snow depth
354             0         0          0
34
          date  maximum temperature  minimum temperature  average temperature  \
349 2016-12-15                   34                   19                 26.5

    precipitation snow fall snow depth
349             0         T          0
35
          date  maximum temperature  minimum temperature  average temperature  \
23  2016-01-24                   35                   20                 27.5
45  2016-02-15                   35                   13                 24.0
344 2016-12-10                   35                   28                 31.5
345 2016-12-11                   35                   28                 31.5

    precipitation snow fall snow depth
23              T         T         22
45           0.44       1.4          0
344             0         0          0
345          0.03       0.4          0
36
         date  maximum temperature  minimum temperature  average temperature  \
3  2016-01-04                   36                   14                 25.0
20 2016-01-21                   36                   26                 31.0
39 2016-02-09                   36                   27                 31.5
48 2016-02-18                   36                   27                 31.5
62 2016-03-03                   36                   26                 31.0

   precipitation snow fall snow depth
3              0         0          0
20             0         0          0
39             0         T          T
48             0         0          0
62             0         0          0
37
         date  maximum temperature  minimum temperature  average temperature  \
19 2016-01-20                   37                   27                 32.0

   precipitation snow fall snow depth
19             0         0          T
38
         date  maximum temperature  minimum temperature  average temperature  \
13 2016-01-14                   38                   22                 30.0

   precipitation snow fall snow depth
13             0         T          0
39
          date  maximum temperature  minimum temperature  average temperature  \
24  2016-01-25                   39                   28                 33.5
29  2016-01-30                   39                   28                 33.5
38  2016-02-08                   39                   28                 33.5
40  2016-02-10                   39                   31                 35.0
47  2016-02-17                   39                   35                 37.0
49  2016-02-19                   39                   24                 31.5
56  2016-02-26                   39                   27                 33.0
63  2016-03-04                   39                   30                 34.5
343 2016-12-09                   39                   29                 34.0
351 2016-12-17                   39                   24                 31.5

    precipitation snow fall snow depth
24              0         0         19
29              0         0          6
38           0.05       0.1          0
40           0.01         T          0
47              0         0          0
49              0         0          0
56              0         0          0
63           0.11       0.4          T
343             0         0          0
351          0.73       2.8          2
40
          date  maximum temperature  minimum temperature  average temperature  \
1   2016-01-02                   40                   32                 36.0
10  2016-01-11                   40                   26                 33.0
36  2016-02-06                   40                   30                 35.0
53  2016-02-23                   40                   35                 37.5
355 2016-12-21                   40                   30                 35.0
362 2016-12-28                   40                   34                 37.0
364 2016-12-30                   40                   33                 36.5

    precipitation snow fall snow depth
1               0         0          0
10              0         0          0
36              0         0          0
53            0.3         T          0
355             0         0          0
362             0         0          0
364          0.01         T          0
41
          date  maximum temperature  minimum temperature  average temperature  \
5   2016-01-06                   41                   25                 33.0
28  2016-01-29                   41                   30                 35.5
57  2016-02-27                   41                   26                 33.5
64  2016-03-05                   41                   28                 34.5
325 2016-11-21                   41                   36                 38.5
326 2016-11-22                   41                   37                 39.0

    precipitation snow fall snow depth
5               0         0          0
28              0         0          6
57              0         0          0
64              0         0          0
325             0         0          0
326             0         0          0
42
          date  maximum temperature  minimum temperature  average temperature  \
0   2016-01-01                   42                   34                 38.0
16  2016-01-17                   42                   30                 36.0
27  2016-01-28                   42                   32                 37.0
324 2016-11-20                   42                   34                 38.0
348 2016-12-14                   42                   34                 38.0

    precipitation snow fall snow depth
0               0         0          0
16           0.05       0.4          0
27              0         0          6
324          0.31         T          0
348             0         0          0
43
          date  maximum temperature  minimum temperature  average temperature  \
79  2016-03-20                   43                   32                 37.5
95  2016-04-05                   43                   26                 34.5
99  2016-04-09                   43                   36                 39.5
347 2016-12-13                   43                   35                 39.0

    precipitation snow fall snow depth
79           0.07         T          0
95              0         0          0
99           0.11         T          0
347             0         0          0
44
          date  maximum temperature  minimum temperature  average temperature  \
11  2016-01-12                   44                   25                 34.5
35  2016-02-05                   44                   31                 37.5
65  2016-03-06                   44                   32                 38.0
365 2016-12-31                   44                   31                 37.5

    precipitation snow fall snow depth
11              0         T          0
35           0.53       2.5          1
65              0         0          0
365             0         0          0
45
          date  maximum temperature  minimum temperature  average temperature  \
2   2016-01-03                   45                   35                 40.0
94  2016-04-04                   45                   29                 37.0
327 2016-11-23                   45                   35                 40.0
342 2016-12-08                   45                   35                 40.0

    precipitation snow fall snow depth
2               0         0          0
94           0.47         T          0
327             0         0          0
342             0         0          0
46
          date  maximum temperature  minimum temperature  average temperature  \
6   2016-01-07                   46                   31                 38.5
7   2016-01-08                   46                   31                 38.5
78  2016-03-19                   46                   36                 41.0
340 2016-12-06                   46                   37                 41.5
341 2016-12-07                   46                   40                 43.0
346 2016-12-12                   46                   34                 40.0
363 2016-12-29                   46                   33                 39.5

    precipitation snow fall snow depth
6               0         0          0
7               0         0          0
78              0         0          0
340          0.35         0          0
341          0.09         0          0
346           0.5         0          0
363          0.39         0          0
47
          date  maximum temperature  minimum temperature  average temperature  \
8   2016-01-09                   47                   40                 43.5
26  2016-01-27                   47                   34                 40.5
37  2016-02-07                   47                   33                 40.0
337 2016-12-03                   47                   41                 44.0
338 2016-12-04                   47                   39                 43.0
357 2016-12-23                   47                   38                 42.5
358 2016-12-24                   47                   38                 42.5

    precipitation snow fall snow depth
8               T         0          0
26              T         0          9
37              0         0          0
337             T         0          0
338             0         0          0
357             0         0          0
358          0.47         0          0
48
          date  maximum temperature  minimum temperature  average temperature  \
25  2016-01-26                   48                   38                 43.0
96  2016-04-06                   48                   30                 39.0
328 2016-11-24                   48                   38                 43.0

    precipitation snow fall snow depth
25              0         0         17
96              0         0          0
328          0.03         0          0
49
          date  maximum temperature  minimum temperature  average temperature  \
339 2016-12-05                   49                   38                 43.5
356 2016-12-22                   49                   37                 43.0

    precipitation snow fall snow depth
339          0.19         0          0
356             0         0          0
50
          date  maximum temperature  minimum temperature  average temperature  \
32  2016-02-02                   50                   38                 44.0
80  2016-03-21                   50                   32                 41.0
93  2016-04-03                   50                   34                 42.0
98  2016-04-08                   50                   40                 45.0
100 2016-04-10                   50                   31                 40.5
316 2016-11-12                   50                   37                 43.5
330 2016-11-26                   50                   40                 45.0
331 2016-11-27                   50                   39                 44.5
359 2016-12-25                   50                   36                 43.0
360 2016-12-26                   50                   33                 41.5

    precipitation snow fall snow depth
32              0         0          T
80           0.06       0.5          T
93           0.09         T          0
98           0.01         0          0
100             0         0          0
316             0         0          0
330             0         0          0
331             0         0          0
359             0         0          0
360          0.02         0          0
51
          date  maximum temperature  minimum temperature  average temperature  \
14  2016-01-15                   51                   34                 42.5
73  2016-03-14                   51                   40                 45.5
121 2016-05-01                   51                   45                 48.0
299 2016-10-26                   51                   38                 44.5
301 2016-10-28                   51                   42                 46.5
336 2016-12-02                   51                   40                 45.5

    precipitation snow fall snow depth
14              T         0          0
73           0.29         0          0
121          0.16         0          0
299             0         0          0
301             0         0          0
336             0         0          0
52
          date  maximum temperature  minimum temperature  average temperature  \
15  2016-01-16                   52                   42                 47.0
52  2016-02-22                   52                   38                 45.0
60  2016-03-01                   52                   39                 45.5
124 2016-05-04                   52                   48                 50.0
298 2016-10-25                   52                   43                 47.5
332 2016-11-28                   52                   38                 45.0

    precipitation snow fall snow depth
15           0.24         0          0
52              0         0          0
60              0         0          0
124          0.01         0          0
298             0         0          0
332             0         0          0
53
          date  maximum temperature  minimum temperature  average temperature  \
88  2016-03-29                   53                   40                 46.5
311 2016-11-07                   53                   41                 47.0

    precipitation snow fall snow depth
88              0         0          0
311             0         0          0
54
          date  maximum temperature  minimum temperature  average temperature  \
46  2016-02-16                   54                   35                 44.5
126 2016-05-06                   54                   48                 51.0
304 2016-10-31                   54                   44                 49.0
329 2016-11-25                   54                   45                 49.5
335 2016-12-01                   54                   42                 48.0

    precipitation snow fall snow depth
46           1.01         0          0
126          0.54         0          0
304             0         0          0
329          0.02         0          0
335          0.07         0          0
55
          date  maximum temperature  minimum temperature  average temperature  \
51  2016-02-21                   55                   44                 49.5
61  2016-03-02                   55                   29                 42.0
83  2016-03-24                   55                   44                 49.5
85  2016-03-26                   55                   38                 46.5
86  2016-03-27                   55                   43                 49.0
300 2016-10-27                   55                   40                 47.5

    precipitation snow fall snow depth
51           0.03         0          0
61           0.14         0          0
83              0         0          0
85              0         0          0
86              0         0          0
300          1.41         0          0
56
          date  maximum temperature  minimum temperature  average temperature  \
30  2016-01-31                   56                   36                 46.0
81  2016-03-22                   56                   35                 45.5
89  2016-03-30                   56                   37                 46.5
123 2016-05-03                   56                   51                 53.5
314 2016-11-10                   56                   40                 48.0
319 2016-11-15                   56                   47                 51.5

    precipitation snow fall snow depth
30              0         0          4
81              0         0          0
89              0         0          0
123          0.61         0          0
314             0         0          0
319          1.81         0          0
57
          date  maximum temperature  minimum temperature  average temperature  \
74  2016-03-15                   57                   44                 50.5
77  2016-03-18                   57                   42                 49.5
125 2016-05-05                   57                   46                 51.5
295 2016-10-22                   57                   47                 52.0

    precipitation snow fall snow depth
74              0         0          0
77              0         0          0
125             0         0          0
295          0.29         0          0
58
          date  maximum temperature  minimum temperature  average temperature  \
97  2016-04-07                   58                   48                 53.0
103 2016-04-13                   58                   40                 49.0
119 2016-04-29                   58                   45                 51.5
305 2016-11-01                   58                   40                 49.0
334 2016-11-30                   58                   50                 54.0
352 2016-12-18                   58                   31                 44.5

    precipitation snow fall snow depth
97           0.09         0          0
103             0         0          0
119          0.05         0          0
305             0         0          0
334          0.73         0          0
352          0.04         0          1
59
          date  maximum temperature  minimum temperature  average temperature  \

In [57]:
g.get_group(60)

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth
54,2016-02-24,60,36,48.0,1.22,0,0
58,2016-02-28,60,38,49.0,0,0,0
66,2016-03-07,60,36,48.0,0,0,0
116,2016-04-26,60,47,53.5,0.24,0,0
122,2016-05-02,60,45,52.5,0.04,0,0
127,2016-05-07,60,48,54.0,0,0,0
333,2016-11-29,60,51,55.5,2.2,0,0
361,2016-12-27,60,40,50.0,0,0,0

In [64]:
df.columns = df.columns.str.strip()
print(df.dtypes)
g = df.groupby('date')
print(g.max(numeric_only=True))

city           object
temperature     int64
humidity        int64
dtype: object

KeyError: 'date'

In [66]:
# Select specific numeric columns for the mean calculation
# Ensure to exclude non-numeric columns like 'date'
numeric_cols = df.select_dtypes(include=['number']).columns
print(g[numeric_cols].mean())

KeyError: "Columns not found: 'humidity', 'temperature'"

In [60]:
# concatinatino of dataframes
india_weather = pd.DataFrame({ # saving dataframes using dictionaries
    "city": ["mumbai","delhi","bangalore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78

In [61]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [62]:
df = pd.concat([india_weather, us_weather])
df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
0   new york           21        68
1    chicago           14        65
2    orlando           35        75

In [63]:
df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
0   new york           21        68
1    chicago           14        65
2    orlando           35        75

In [67]:
df = pd.concat([india_weather, us_weather], axis=1)
df

        city  temperature  humidity      city  temperature  humidity
0     mumbai           32        80  new york           21        68
1      delhi           45        60   chicago           14        65
2  bangalore           30        78   orlando           35        75

In [68]:
# merge dataframes
temperature_df = pd.DataFrame({
    "city": ["mumbai","delhi","bangalore", 'hyderabad'],
    "temperature": [32,45,30,40]})
temperature_df

        city  temperature
0     mumbai           32
1      delhi           45
2  bangalore           30
3  hyderabad           40

In [69]:
humidity_df = pd.DataFrame({
    "city": ["delhi","mumbai","bangalore"],
    "humidity": [68, 65, 75]})
humidity_df

        city  humidity
0      delhi        68
1     mumbai        65
2  bangalore        75

In [70]:
df = pd.merge(temperature_df, humidity_df, on='city')
df

        city  temperature  humidity
0     mumbai           32        65
1      delhi           45        68
2  bangalore           30        75

In [71]:
# outer join
df = pd.merge(temperature_df, humidity_df, on='city', how='outer')
df

        city  temperature  humidity
0  bangalore           30      75.0
1      delhi           45      68.0
2  hyderabad           40       NaN
3     mumbai           32      65.0

In [72]:
# numerical indexing
df = pd.DataFrame([1,2,3,4,5,6,7,8,9,19], index=[49,48,47,46,45, 1, 2, 3, 4, 5])
df

     0
49   1
48   2
47   3
46   4
45   5
1    6
2    7
3    8
4    9
5   19

In [77]:
s = pd.Series([10, 20, 30, 40, 50])
print(s.loc[:2])  # Prints values at index 0, 1, 2

0    10
1    20
2    30
dtype: int64

In [78]:
s.iloc[:2]

0    10
1    20
dtype: int64